# Generated by Django 5.1.4 on 2025-01-15 09:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fooddeliveryapp', '0004_addproduct'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='addproduct',
            new_name='addmenu',
        ),
    ]
