# Generated by Django 5.1.4 on 2025-01-15 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddeliveryapp', '0005_rename_addproduct_addmenu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addmenu',
            name='Appetizer',
        ),
        migrations.RemoveField(
            model_name='addmenu',
            name='Beverages',
        ),
        migrations.RemoveField(
            model_name='addmenu',
            name='Dessert',
        ),
        migrations.RemoveField(
            model_name='addmenu',
            name='MainCourse',
        ),
        migrations.AddField(
            model_name='addmenu',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='addmenu',
            name='FoodName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
