# Generated by Django 5.1.4 on 2025-01-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddeliveryapp', '0006_remove_addmenu_appetizer_remove_addmenu_beverages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmenu',
            name='Category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
