# Generated by Django 5.1.4 on 2025-01-16 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddeliveryapp', '0007_alter_addmenu_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmenu',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fooddeliveryapp.restaurentsignup'),
        ),
    ]
