# Generated by Django 5.1.4 on 2025-01-20 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddeliveryapp', '0008_alter_addmenu_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurentsignup',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
