# Generated by Django 5.1.4 on 2025-01-22 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddeliveryapp', '0009_restaurentsignup_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addmenu',
            old_name='Category',
            new_name='quantity',
        ),
        migrations.CreateModel(
            name='product_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('total', models.CharField(max_length=100, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fooddeliveryapp.addmenu')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fooddeliveryapp.customersignup')),
            ],
        ),
    ]
