# Generated by Django 5.1.4 on 2025-01-23 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddeliveryapp', '0010_rename_category_addmenu_quantity_product_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FoodName', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('price', models.DateField(null=True)),
                ('quantity', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approve', 'Approve'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fooddeliveryapp.restaurentsignup')),
            ],
        ),
    ]
