# Generated by Django 5.1.4 on 2025-01-23 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fooddeliveryapp', '0011_userbook'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Userbook',
            new_name='customerbook',
        ),
    ]
