# Generated by Django 5.1.4 on 2025-01-23 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fooddeliveryapp', '0012_rename_userbook_customerbook'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customerbook',
        ),
    ]
