# Generated by Django 5.1.4 on 2025-01-24 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fooddeliveryapp', '0013_delete_customerbook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentsignup',
            name='restaurent',
        ),
    ]
