# Generated by Django 5.1.4 on 2025-01-27 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddeliveryapp', '0014_remove_agentsignup_restaurent'),
    ]

    operations = [
        migrations.CreateModel(
            name='assigned_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fooddeliveryapp.agentsignup')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fooddeliveryapp.customersignup')),
            ],
        ),
    ]
