# Generated by Django 5.1.4 on 2025-01-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddeliveryapp', '0016_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsignup',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
