# Generated by Django 5.1.4 on 2025-01-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddeliveryapp', '0017_agentsignup_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigned_order',
            name='FoodName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
