# Generated by Django 5.1.4 on 2025-01-28 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddeliveryapp', '0018_assigned_order_foodname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assigned_order',
            name='FoodName',
        ),
        migrations.AlterField(
            model_name='assigned_order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fooddeliveryapp.product_cart'),
        ),
    ]
