# Generated by Django 5.1.4 on 2025-01-30 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddeliveryapp', '0021_alter_assigned_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentsignup',
            name='status',
            field=models.CharField(default='available', max_length=100, null=True),
        ),
    ]
