# Generated by Django 5.1.4 on 2025-01-31 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddeliveryapp', '0023_agentworks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmenu',
            name='quantity',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
