# Generated by Django 5.1.4 on 2025-01-31 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddeliveryapp', '0024_alter_addmenu_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmenu',
            name='price',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
