# Generated by Django 5.1.4 on 2025-01-31 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddeliveryapp', '0025_alter_addmenu_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmenu',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='addmenu',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
